### PR TITLE
Create Tool to help more feature

### PR DESCRIPTION
**Pull request by gguysm10**
# Tool (a commit by JungHaha)
## About me
- I'm a people want to do something when i'm have free time!
- I think that you should to create a tool modal box with a lot to people enjoy it! Like draw, note, share the screen,... and more
- So i create this pull to tell you about it
## Project Example
Create a Modal Box and show app

Preview (Note)
Preview

## Branch Available
You can merge if you want this structure

## Bonus+++ 
This is the icon i have draw for you
Icon

### CODE REVIEW

**Review by gguysm10 — COMMENTED** [review]
Preview

**Comment by gguysm10** [comment]
### Video Talk via Meet Now by bTeam

I'm have opened new room to help you talk about this pull request: [Join this Meet via Meet Now](https://bhostvideo-meeting-v1.herokuapp.com/randompx4vg4spduso37zhm944u8m7d9m7kc-bte3m4rume-1affc7fc-bteamforum-github-pullrequesst17-junghaha020-id57d93efe-5495-4e42-8fe6-4ae38bc5fb64-id294adca1b-d946-46ff-996f-2a9198cb5c0c-id355af1e37-0734-46d8-b070-a1e42e4fc392-idpassswordjnewr4gcf55zp4mvjo5dyg7phrxtcq-hashv4-restrictedno-nextpssshs9frrujbnbw097h3n43nponlklw6h-branchgit17-utmsource-githubmarkdown-pullurl-comment)

  _*Note: Please read Important Note before join_

### Use and preview

You can use this link to talk together in Meet by bTeam. Here is the UI when i get url:

Capture

### Important Note
- This link is public, everyone will see you if they join, then please don't do something crazy ;)
- Turn off webcam if you don't... ready to go
- Should follow GitHub's [Community Guidelines](https://docs.github.com/articles/github-community-guidelines)

**Comment by bteamapp** [comment]
I can't join the meet! Haha! :)

**Comment by bteamapp** [comment]
### Forum
I think I'll create a discussion about this!

**Pull request merged**
